### ISSUE TITLE
make up mongo error

### ISSUE THREAD

**Issue by sallenhandong** [zeromicro/cds#92]
mongodb `test_mongo`.`example` inserted 10000 lines
Traceback (most recent call last):
  File "/tmp/init_db.py", line 74, in <module>
    init_mongo()
  File "/tmp/init_db.py", line 69, in init_mongo
    collection.insert_many(result)
  File "/usr/local/lib/python3.10/site-packages/pymongo/collection.py", line 615, in insert_many
    blk.execute(write_concern, session=session)
  File "/usr/local/lib/python3.10/site-packages/pymongo/bulk.py", line 459, in execute
    return self.execute_command(generator, write_concern, session)
  File "/usr/local/lib/python3.10/site-packages/pymongo/bulk.py", line 351, in execute_command
    with client._tmp_session(session) as s:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1656, in _tmp_session
    s = self._ensure_session(session)
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1643, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1594, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1629, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 534, in get_server_session
    session_timeout = self._check_session_support()
  File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 520, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 223, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo1:30001: [Errno -2] Name or service not known,mongo2:30002: [Errno -2] Name or service not known,mongo3:30003: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 624a83e9fd437d56bbaaf7a3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None, error=AutoReconnect('mongo1:30001: [Errno -2] Name or service not known')>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None, error=AutoReconnect('mongo2:30002: [Errno -2] Name or service not known')>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno -2] Name or service not known')>]>
make: *** [init] Error 1

**Comment by Mycheers** [comment]
遇到同样的问题如何处理呢？
